// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckServerHealth() {
  return window['go']['main']['App']['CheckServerHealth']();
}

export function ConfirmExit() {
  return window['go']['main']['App']['ConfirmExit']();
}

export function IsHostUser() {
  return window['go']['main']['App']['IsHostUser']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function ScanLANServers() {
  return window['go']['main']['App']['ScanLANServers']();
}

export function SetLoggedIn(arg1) {
  return window['go']['main']['App']['SetLoggedIn'](arg1);
}

export function SetRoomHostActive(arg1) {
  return window['go']['main']['App']['SetRoomHostActive'](arg1);
}

export function SetWorkspaceActive(arg1) {
  return window['go']['main']['App']['SetWorkspaceActive'](arg1);
}
