// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmExit() {
  return window['go']['main']['App']['ConfirmExit']();
}

export function IsHostUser() {
  return window['go']['main']['App']['IsHostUser']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}
