// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckServerHealth():Promise<boolean>;

export function ConfirmExit():Promise<void>;

export function IsHostUser():Promise<boolean>;

export function OpenFile():Promise<string>;

export function SaveFile(arg1:string):Promise<string>;

export function ScanLANServers():Promise<Array<main.LANServer>>;

export function SetLoggedIn(arg1:boolean):Promise<void>;

export function SetRoomHostActive(arg1:boolean):Promise<void>;

export function SetWorkspaceActive(arg1:boolean):Promise<void>;
