// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmExit():Promise<void>;

export function IsHostUser():Promise<boolean>;

export function OpenFile():Promise<string>;

export function SaveFile(arg1:string):Promise<string>;
